import turtle
a=turtle.Pen()
a.color('black')
a.circle(130)
a.left(72)
a.color('blue')
a.circle(130)
a.left(72)
a.color('gray')
a.circle(130)
a.left(72)
a.color('red')
a.circle(130)
a.left(72)
a.color('purple')
a.circle(130)
a.left(72)